/*
This module is responsible to take in the raw tokens generated by the tokenizer and structure it in a  way so taht
every other module can use  it in a meaningful way. The algorithm is not of much complexity it's a very simple the first
item in the tokens array is the program user wants to run so we extrcat it out which will be kept in the command struct as
command.program and for the arguments until the item is an > or >> or 2> we can be sure that it's an argument so we push them
to the argument array which can be accessed from command.argument. Now the moment we get a redirection item like >>, 2>, > we match them and based on the redirection we create the Redirect struct from it and push that to a redirections array which is accessed as command.redirections.
*/

#[derive(Debug)]
pub enum Stream {
    STDOUT,
    STDERR,
    STDIN,
}
#[derive(Debug)]
pub enum Mode {
    OVERWRITE,
    APPEND,
}
#[derive(Debug)]
pub struct Redirect {
    pub target: String,
    pub stream: Stream,
    pub mode: Mode,
}

pub struct Command {
    pub program: String,
    pub arguments: Vec<String>,
    pub redirects: Vec<Redirect>,
    pub piped_command: Option<Box<Command>>,
}

impl Redirect {
    fn new(target: String, stream: Stream, mode: Mode) -> Self {
        Redirect {
            target,
            stream,
            mode,
        }
    }
}

impl Command {
    pub fn new(tokens: Vec<String>) -> Self {
        let program = tokens[0].clone();
        let mut arguments = Vec::new();
        let mut redirects = Vec::new();
        let mut piped_command = None;
        let mut pos = 1;

        while pos < tokens.len() {
            match tokens[pos].as_str() {
                ">" if pos + 1 < tokens.len() => {
                    redirects.push(Redirect::new(
                        tokens[pos + 1].clone(),
                        Stream::STDOUT,
                        Mode::OVERWRITE,
                    ));
                    pos += 2;
                }
                ">>" if pos + 1 < tokens.len() => {
                    redirects.push(Redirect::new(
                        tokens[pos + 1].clone(),
                        Stream::STDOUT,
                        Mode::APPEND,
                    ));
                    pos += 2;
                }
                "2>" if pos + 1 < tokens.len() => {
                    redirects.push(Redirect::new(
                        tokens[pos + 1].clone(),
                        Stream::STDERR,
                        Mode::OVERWRITE,
                    ));
                    pos += 2;
                }

                "|" => {
                    piped_command = Some(Box::new(Command::new(tokens[pos + 1..].to_vec())));
                    break;
                }
                _ => {
                    arguments.push(tokens[pos].clone());
                    pos += 1;
                }
            }
        }

        Command {
            piped_command,
            program,
            arguments,
            redirects,
        }
    }
}
